c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py:36: SyntaxWarning: invalid escape sequence '\.'
  if len(re.findall("/.*\..*",path))==0:
c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py:68: SyntaxWarning: invalid escape sequence '\/'
  u.pathname = u.pathname.replace(/\/+$/, ''); // remove trailing slash
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/ss/k=xjs.hd.MXPpeGkMgS0.L.W.O/am=AKFUIAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAAYgOwIAAAAQAAAkgJAAAAACAAIAAAAgAACAAAAAAAAIAAgAAgASAIAAAAQAAAABBAAAAAAIAEAAEkAUQAAAACUhAYAQAAAAQAAGgABAEAAAAEAAAAAQAgAAAAAAAAAQAAAgAAgABZACAgVQOkBUBAAAAEAAgIAAAAIAAIADAEQAgCeAAIYAAAAEAQAAOgBAAAIAAQEAAAAAAAAgBEAAAMAIABDEAMAAAAAAAAAIAAAAAAABgAAAAAAAAAAAAAAAAAAIABAABEAKAAAAAAAAAAAAAAAAAAAAAAAACAAAAQ'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  [Previous line repeated 2 more times]
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAIAIAAAAAABAAEgAAAAAAAAAAAAAigAACAAAAAAAAAAIAAAAADAIAAAAYAAAAAAAAAAAQAAEAAACAAeAPAAgAgAAJAAAAAAAAAHABAEQAAAoAAAAAAAAAAAAAIAAAAAAAgAAAAAAAAAAUAAAAAAAAQAAAAAAAAAAABAAABAgAAAAAAAAAAAAAAAAAAOgBAAAAAAAAAAAAAAAAgAMAABEAAABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSKAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/ck=xjs.hd.MXPpeGkMgS0.L.W.O/am=AKFUIAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAAYoO4IAAAAQBAAkgJAAAAACAAIAAAigAACAAAAAAAAIAIgAAgATAIAAAAYAAAABBAAAAAQIAEAAEmAUeAPAAiUhAYJQAAAAQAAGnABAEQAAAsAAAAAQAgAAAAAIAAAQAAAgAAgABZACAgVQOkBUBAAQAEAAgIAAAAIBAIADAkQAgCeAAIYAAAAEAQAAOgBAAAIAAQEAAAAAAAAgBMAABMAIABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSKAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  [Previous line repeated 1 more time]
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/ck=xjs.hd.MXPpeGkMgS0.L.W.O/am=AKFUIAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAIAAAABAAAAAAAAAAAYoO4IAAAAQBAAkgJAAAAACAAIAAAigAACAAAAAAAAIAIgAAgATAIAAAAYAAAABBAAAAAQIAEAAEmAUeAPAAiUhAYJQAAAAQAAGnABAEQAAAsAAAAAQAgAAAAAIAAAQAAAgAAgABZACAgVQOkBUBAAQAEAAgIAAAAIBAIADAkQAgCeAAIYAAAAEAQAAOgBAAAIAAQEAAAAAAAAgBMAABMAIABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSKAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAIAIAAAAAABAAEgAAAAAAAAAAAAAiAAACAAAAAAAAAAIAAAAADAIAAAAYAAAAAAAAAAAQAAEAAACAAeAPAAgAgAAJAAAAAAAAAHABAEQAAAoAAAAAAAAAAAAAIAAAAAAAgAAAAAAAAAAUAAAAAAAAQAAAAAAAAAAABAAABAgAAAAAAAAAAAAAAAAAAOgBAAAAAAAAAAAAAAAAgAMAABEAAABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSCAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAIAIAAAAAABAAEgAAAAAAAAAAAAAiAAACAAAAAAAAAAIAAAAADAIAAAAYAAAAAAAAAAAQAAEAAACAAeAPAAgAgAAJAAAAAAAAAHABAEQAAAoAAAAAAAAAAAAAIAAAAAAAgAAAAAAAAAAUAAAAAAAAQAAAAAAAAAAABAAABAgAAAAAAAAAAAAAAAAAAOgBAAAAAAAAAAAAAAAAgAMAABEAAABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSCAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
Error occurred in event listener
Traceback (most recent call last):
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 453, in dispatch
    g.switch(self._replace_guids_with_channels(params))
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_connection.py", line 444, in _listener_with_error_handler_attached
    potential_future = listener(params)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 177, in <lambda>
    lambda params: self._on_request(
                   ~~~~~~~~~~~~~~~~^
        from_channel(params["request"]),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from_nullable_channel(params.get("page")),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ),
    ^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_browser_context.py", line 709, in _on_request
    page.emit(Page.Events.Request, request)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 220, in emit
    handled = self._call_handlers(event, args, kwargs)
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 196, in _call_handlers
    self._emit_run(f, args, kwargs)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 81, in _emit_run
    self.emit("error", exc)
    ~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 70, in emit
    return super().emit(event, *args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 223, in emit
    self._emit_handle_potential_error(event, args[0] if args else None)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\base.py", line 181, in _emit_handle_potential_error
    raise error
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\pyee\asyncio.py", line 79, in _emit_run
    coro: Any = f(*args, **kwargs)
                ~^^^^^^^^^^^^^^^^^
  File "C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\_impl\_impl_to_api_mapping.py", line 123, in wrapper_func
    return handler(
        *list(map(lambda a: self.from_maybe_impl(a), args))[:arg_count]
    )
  File "c:\Users\teren\Docs and Files\Github_Repos\Python\scraaaape.py", line 211, in rqhandle
    os.makedirs(os.path.dirname("scraped/"+sanitize_url_for_filename(remove_https(add_html_extension(request.url)))), exist_ok=True)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 218, in makedirs
  File "<frozen os>", line 228, in makedirs
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'scraped/www.google.com/xjs/_/js/k=xjs.hd.en.tWOAPdWg9SI.es5.O/am=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAAIAIAAAAAABAAEgAAAAAAAAAAAAAiAAACAAAAAAAAAAIAAAAADAIAAAAYAAAAAAAAAAAQAAEAAACAAeAPAAgAgAAJAAAAAAAAAHABAEQAAAoAAAAAAAAAAAAAIAAAAAAAgAAAAAAAAAAUAAAAAAAAQAAAAAAAAAAABAAABAgAAAAAAAAAAAAAAAAAAOgBAAAAAAAAAAAAAAAAgAMAABEAAABDEAMAAAAAAAAAOgAEHjCkpgAAAAAAAAAAAAAAAAAAIEBBMBcSCAgQAAAAAAAAAAAAAAAAAAAAACCkiYUG'
node:events:496
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:63:18)
    at writeOrBuffer (node:internal/streams/writable:572:12)
    at _write (node:internal/streams/writable:501:10)
    at Writable.write (node:internal/streams/writable:510:10)
    at PipeTransport.send (C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\driver\package\lib\server\utils\pipeTransport.js:52:21)
    at dispatcherConnection.onmessage (C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:60:59)
    at DispatcherConnection.sendEvent (C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:168:10)
    at BrowserContextDispatcher._dispatchEvent (C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:109:22)
    at CRBrowserContext.<anonymous> (C:\Users\teren\Docs and Files\python_venvs\py313_base\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\browserContextDispatcher.js:124:12)
    at CRBrowserContext.emit (node:events:518:28)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:170:8)
    at emitErrorCloseNT (node:internal/streams/destroy:129:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

Node.js v22.14.0
